- name: initial updates
  hosts: all
  tasks:
    # - name: update pi before starting
      # ansible.builtin.apt:
        # update_cache: yes
        # cache_valid_time: 3600
    # 


    - name: Purge unattended upgrades
      raw: apt-get -y purge unattended-upgrades

    - name: perform upgrades
      apt:
        update_cache: true
        update_cache_retries: 10
        update_cache_retry_max_delay: 20
        upgrade: dist
        autoremove: yes

    - name: install required python dependencies
      apt:
        name:
          - python3
          - python3-dev
          - python3-pip
          - python3-numpy
          - python3-pandas
          - python3-wheels
          - python3-setuptools
          - python3-cython
          - build-essential
          - ninja-build
          - g++
          - pkgconf
          - libgfortran5
          - gfortran
          - libopenblas-dev
          - liblapack-dev
          - libblas-dev
        state: latest

#apt install libblas3 liblapack3 liblapack-dev libblas-dev gfortran