- name: setup mqtt and database
  hosts: all
  tasks:

    - name: install sqlite3
      ansible.builtin.package:
        name: sqlite3
        state: present

    - name: install python mqtt client
      ansible.builtin.pip:
       name: paho-mqtt

    - name: copy python script for mqtt_logger_service
      tags: logger
      ansible.builtin.copy:
        src: ../setup_files/mqtt_logger/
        dest: /etc/mqtt_logger/
        force: yes
        mode: 0755

    - name: copy mqtt_logger systemd service setup file
      ansible.builtin.copy:
        src: ../setup_files/mqtt_logger.service
        dest: /lib/systemd/system/mqtt_logger.service
        force: yes
        mode: 0644

    # read AND write permissions for all users needed
    - name: make sure db file exists
      ansible.builtin.file:
        path: /home/beta/sensor_data.db
        state: touch
        mode: 0666
        owner: root

    - name: install database
      command: python /etc/mqtt_logger/models.py

    - name: start mqtt_logger
      ansible.builtin.systemd:
        name: mqtt_logger
        enabled: true
        masked: false
        state: restarted
