- name: Setup mqtt and database
  hosts: all
  tasks:

    - name: Install sqlite3
      apt:
        name: sqlite3
        state: latest

    - name: Copy mqtt_logger systemd service setup file
      ansible.builtin.copy:
        src: ../setup_files/mqtt_logger.service
        dest: /lib/systemd/system/mqtt_logger.service
        force: true
        mode: 664

    # read AND write permissions for all users needed
    - name: Make sure db file exists
      ansible.builtin.file:
        path: /home/beta/sensor_data.db
        state: touch
        mode: "0666"
        owner: root

    - name: Intialize db
      command:
        cmd: /home/beta/sensor-hub/bin/initialize_database /home/beta/sensor_data.db

    - name: Start mqtt_logger
      ansible.builtin.systemd:
        name: mqtt_logger
        enabled: true
        masked: false

    - name: Reload systemd daemon
      ansible.builtin.systemd:
        daemon_reload: true
