- name: setup mqtt and database
  hosts: all
  tasks:

    - name: install sqlite3
      ansible.builtin.package:
        name: sqlite3
        state: present

    - name: copy mqtt_logger systemd service setup file
      ansible.builtin.copy:
        src: ../setup_files/mqtt_logger.service
        dest: /lib/systemd/system/mqtt_logger.service
        force: yes
        mode: 0644

    # read AND write permissions for all users needed
    - name: make sure db file exists
      ansible.builtin.file:
        path: /home/beta/sensor_data.db
        state: touch
        mode: 0666
        owner: root

    - name: install mqtt-db-logger
      ansible.builtin.pip:
        name: git+https://github.com/4cscc/mqtt-data-logger.git@main

    - name: start mqtt_logger
      ansible.builtin.systemd:
        name: mqtt_logger
        enabled: true
        masked: false
        state: restarted
