- name: Access point and network setup.
  hosts: all
  tasks:

    - name: Initialize hosted network.
      community.general.nmcli:
        type: wifi
        conn_name: Hotspot
        ifname: wlan0
        autoconnect: true
        wifi_sec:
          key-mgmt: wpa-psk
          psk: FourCorners
        ssid: sensor_hub
        wifi:
          mode: ap
        state: present
        ip4:
          - 10.42.0.1/24
