- name: access point and network setup
  hosts: all
  tasks:

  # install hostapd
  - name: install hostapd
    apt:
      name: hostapd
      state: present

  # unmask hostapd
  - name: unmask hostapd
    shell: systemctl unmask hostapd

  # enable hostapd
  - name: enable hostapd
    shell: systemctl enable hostapd

  # install dnsmasq
  - name: install dnsmasq
    apt:
      name: dnsmasq
      state: present

  # install iptables-persistent
  - name: install iptables-persistent
    apt:
      name: iptables-persistent
      state: present

  # install netfilter-persistent
  - name: install netfilter-persistent
    apt:
      name: netfilter-persistent
      state: present

  ### setup the network router

  # remove old dhcpcd.conf
  - name: remove old dhcpcd.conf
    file:
      path: /etc/dhcpcd.conf
      state: absent

  # copy new dhcpcd.conf
  - name: copy new dhcpcd.conf
    copy:
      src: ../setup_files/dhcpcd.conf
      dest: /etc/dhcpcd.conf
      owner: root
      group: root
      mode: 0644

  # remove old dnsmasq.conf
  - name: remove old dnsmasq.conf
    file:
      path: /etc/dnsmasq.conf
      state: absent

  
  # ensure dnsmasq.leases exists
  - name: ensure dnsmasq.lease
    file:
      path: /var/lib/misc/dnsmasq.leases
      state: touch
      mode: 0666

  # copy new dnsmasq.conf
  - name: copy new dnsmasq.conf
    copy:
      src: ../setup_files/dnsmasq.conf
      dest: /etc/dnsmasq.conf
      owner: root
      group: root
      mode: 0644

  
  # set permissions for dnsmasq.leases
  # - name: set permissions for dnsmasq.leases
    # file:
      # path: /var/lib/misc/dnsmasq.leases
      # mode: 0666
# 
  # ensure dnsmasq service is running
  - name: ensure dnsmasq service is running
    service:
      name: dnsmasq
      state: restarted
      enabled: yes
      masked: no

  # ensure wifi is not blocked
  - name: ensure wifi is not blocked
    shell: rfkill unblock wlan 

  # upload hostapd.conf
  - name: upload hostapd.conf
    copy:
      src: ../setup_files/hostapd.conf
      dest: /etc/hostapd/hostapd.conf
      owner: root
      group: root
      mode: 0644

  - name: ensure hostapd service is running
    service:
      name: hostapd
      state: restarted
      enabled: yes
      masked: no  

  - name: Reboot machine using a custom reboot command
    ansible.builtin.reboot:
      reboot_command: systemctl reboot