# Create directory structure, install necessary software, and configures server
# to produce and server visualizations of the data(and possibly to download
# data?)

- name: setup server
  hosts: all
  tasks:

# TODO: ensure evaluated for security
# TODO: template in username or home location

# source /var/lib/awx/venv/ansible/bin/activate
# umask 0022
# pip install --upgrade pip
# deactivate

# Setup Location for Server
  - name: create viz server environment
    ansible.builtin.file:
      path: "/home/beta/viz/"
      recurse: yes
      state: directory
      mode: 0755

  - name: create virtual environment for server
    ansible.builtin.command:
      cmd: "python -m venv /home/beta/viz/.venv"
  
  - name: copy requirements.txt
    ansible.builtin.copy:
      src: ../setup_files/viz_server/server_requirements.txt
      dest: "/home/beta/viz/requirements.txt"
  
  - name: copy server setup
    ansible.builtin.copy:
      src: ../setup_files/viz_server/vizServer
      dest: /home/beta/viz/

  - name: install server
    ansible.builtin.pip:
      requirements: "/home/beta/viz/requirements.txt"
      virtualenv: "/home/beta/viz/.venv"

  

  # - name: activate server virtual environment
    # ansible.builtin.command:
      # cmd: source ./viz/bin/activate

# Install Software

# flask
# 
  # TODO: template in home
  # - name: install flask + dependencies
    # ansible.builtin.pip:
      # name: Flask
      # virtualenv: ./viz/.venv

  # - name: run flask server
    # ansible.builtin.command:
      # cmd: "flask --app vizServer run --debug"
      
